name: Test React App
on: 
  pull_request:
     types:
       - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'hotfix-*'
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code
              uses: actions/checkout@v3
            - name: Install Node v18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install
              run: npm install
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                folder: build
                branch: gh-pages
              env:
                ACCESS-TOKEN: ${{ secrets.ACCESS_TOKEN }}
